export enum PatientHistoryItemType {
    STANDARD = 'STANDARD',
    PERSONAL_HISTORY = 'PERSONAL_HISTORY',
    PHYSICAL_EXAM = 'PHYSICAL_EXAM',
    PATIENT_SEX = 'PATIENT_SEX',
    PATIENT_OCCUPATION = 'PATIENT_OCCUPATION',
    PATIENT_CIVIL_STATUS = 'PATIENT_CIVIL_STATUS',
    PATIENT_DOCUMENTS = 'PATIENT_DOCUMENTS'
}