export enum CompanyType {
    STANDARD = 'STANDARD',
    SUPPLIER = 'SUPPLIER',
    BENEFICIARY = 'BENEFICIARY',
    COLLABORATOR = 'COLLABORATOR',
    SERVICE = 'SERVICE',
    HEALTH_AGREEMENT = 'HEALTH_AGREEMENT'
}