export enum NotificationType {
    ESTUTURNO = 'ESTUTURNO',
    FALTANCINCO = 'FALTANCINCO',
    FALTAUNO = 'FALTAUNO',
    TUTURNO = 'TUTURNO',
    ENCUESTA = 'ENCUESTA',
    MONTHLY_COMMERCE_STATISTICS = 'MONTHLY_COMMERCE_STATISTICS',
    BOOKING = 'BOOKING',
    WAITLIST = 'WAITLIST',
    BOOKING_CONFIRM = 'BOOKING_CONFIRM',
    ATTENTION_CANCELLED = 'ATTENTION_CANCELLED',
    BOOKING_CANCELLED = 'BOOKING_CANCELLED',
    BOOKING_COMMERCE_CONDITIONS = 'BOOKING_COMMERCE_CONDITIONS',
    POST_ATTENTION = 'POST_ATTENTION'
}