export enum QuestionType {
  PATIENT_HISTORY_ITEM = 'PATIENT_HISTORY_ITEM',
  OPEN_TEXT_FIELD = 'OPEN_TEXT_FIELD',
  OPEN_NUMBER_FIELD = 'OPEN_NUMBER_FIELD',
  YES_OR_NOT = 'YES_OR_NOT',
  OPEN_WRITING = 'OPEN_WRITING',
  OPEN_OPTIONS = 'OPEN_OPTIONS',
  CHOOSE_OPTION = 'CHOOSE_OPTION'
}